apiVersion: v2
name: geojson-viewer
description: A Helm chart for geojson-viewer
type: application
version: 1.0.0
appVersion: 1.0.0
dependencies:
  - name: mclabels
    version: 1.0.1
    repository: oci://<registry>/helm/infra
