apiVersion: v2
name: but-better-geojson-viewer
description: A Helm chart for but-better-geojson-viewer
type: application
version: 0.0.0
appVersion: 0.0.0
dependencies:
  - name: mclabels
    version: 1.0.1
    repository: oci://<registry>/helm/infra
